export const STATUS_OPTIONS = [
   {code: "ALL", label: "All Records"},
  { code: "01", label: "Individual" },
  { code: "03", label: "H.U.F." },
  { code: "05", label: "Firm" },
  { code: "07", label: "AOP", note: "(Including Private Discretionary Trust)" },
  { code: "08", label: "AOP Trust", note: "(Only for ITR-7 Cases)" },
  { code: "09", label: "Body Of Individual" },
  { code: "10", label: "Artificial Juridical Person" },
  { code: "11", label: "Co-Operative Society" },
  { code: "12", label: "Company Public Interested" },
  { code: "13", label: "Company Public Not Interested" },
  { code: "14", label: "Company Private" },
  { code: "16", label: "Local Authority" },
];

export const INITIAL_DATA = [
  { id: 1,  codeNo: 247, name: "AKBARPUR",      fatherName: "", pan: "LKNG33703F", status: "01" },
  { id: 2,  codeNo: 77,  name: "AKHDERA",       fatherName: "", pan: "LKNG34490B", status: "01" },
  { id: 3,  codeNo: 17,  name: "AKOUNI",        fatherName: "", pan: "LKNG07593F", status: "01" },
  { id: 4,  codeNo: 18,  name: "AMDAHI",        fatherName: "", pan: "LKNG42213D", status: "01" },
  { id: 5,  codeNo: 456, name: "ANBHULA",       fatherName: "", pan: "LKNG42209G", status: "01" },
  { id: 6,  codeNo: 425, name: "ASARTHA",       fatherName: "", pan: "ALDG15197A", status: "01" },
  { id: 7,  codeNo: 457, name: "ASHOKPUR",      fatherName: "", pan: "ALDG15787C", status: "01" },
  { id: 8,  codeNo: 458, name: "BABHANI",       fatherName: "", pan: "LKNG33628A", status: "01" },
  { id: 9,  codeNo: 19,  name: "BADLEPUR",      fatherName: "", pan: "LKNG07591D", status: "01" },
  { id: 10, codeNo: 20,  name: "BADNAPUR",      fatherName: "", pan: "LKNG07970E", status: "01" },
  { id: 11, codeNo: 120, name: "BAGULAHI",      fatherName: "", pan: "LKNG34856D", status: "01" },
  { id: 12, codeNo: 248, name: "BAHADURA",      fatherName: "", pan: "LKNG34048A", status: "01" },
  { id: 13, codeNo: 121, name: "BAHARE KUIYAN", fatherName: "", pan: "ALDG13578F", status: "01" },
  { id: 14, codeNo: 167, name: "BAHLOLPUR",     fatherName: "", pan: "ALDG10968G", status: "01" },
  { id: 15, codeNo: 249, name: "BAIJALPUR",     fatherName: "", pan: "LKNG33747A", status: "01" },
  { id: 16, codeNo: 543, name: "BAKIYAPUR",     fatherName: "", pan: "LKNG07971F", status: "01" },
  { id: 17, codeNo: 318, name: "BAKTHORWA",     fatherName: "", pan: "ALDG13707B", status: "01" },
  { id: 18, codeNo: 250, name: "BALAPUR",       fatherName: "", pan: "LKNG33851G", status: "01" },
  { id: 19, codeNo: 372, name: "BALHI JOT",     fatherName: "", pan: "ALDG15540A", status: "01" },
  { id: 20, codeNo: 460, name: "BALLIPUR",      fatherName: "", pan: "LKNG35231A", status: "01" },
  { id: 21, codeNo: 79,  name: "BALPUR HAJARI", fatherName: "", pan: "LKNG30669C", status: "01" },
  { id: 22, codeNo: 168, name: "BALPUR JAT",    fatherName: "", pan: "ALDG10969A", status: "01" },
  { id: 23, codeNo: 373, name: "BALUWA KAKRA",  fatherName: "", pan: "LKNG34461A", status: "01" },
  { id: 24, codeNo: 461, name: "BANDHWA",       fatherName: "", pan: "LKNG33756C", status: "01" },
];

export const EMPTY_FORM = {
  code: "", name: "", fatherName: "", pan: "", status: "",
  address: "", mobile: "", email: "", dob: "", ward: "",
  group: "GENERAL", prefix: "",
  firstName: "", middleName: "", lastName: "", spouseName: "",
  qualification: "", nationality: "", occupation: "",
  uinNo: "", nameAsPerUIN: "", mobileLinkedWithUIN: "",
  passportStatus: "", passportNumber: "", gender: "", votersId: "",
  dod: "", residentialStatus: "", tan: "", din: "",
  dateOfCommencementOfBusiness: "", isFIIFPI: "", sebiRegnNo: "",
  isMSME: "", msmeRegistrationNo: "", msmeRegistrationDate: "",
  enterpriseType: "", majorActivity: "",
  businessName: "", contactPerson: "", natureOfBusiness: "",
  stockValuationMethod: "", gstNo: "", gstStartDate: "", gstEndDate: "",
  vatRegNo: "", centralSalesTaxNo: "", serviceTaxRegNo: "",
  otherRegistration: "",
  signingPersonName: "", signingPersonFatherName: "",
  signingPersonDesignation: "", signingPersonGender: "",
  signingPersonPanNo: "", signingPersonDob: "",
  dateOfFormation: "", dateOfDeed: "",
};