const ROLES = Object.freeze({
  ADMIN: "ADMIN",
  TEAM_LEADER: "TEAM_LEADER",
  TEAM_MEMBER: "TEAM_MEMBER"
});

const STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
});

const USER_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
});

const CLIENT_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
});

const TASK_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  COMPLETED: "COMPLETED",
  OVERDUE: "OVERDUE",
  CANCELLED: "CANCELLED",
});

const PRIORITY = Object.freeze({
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  URGENT: "URGENT",
});

const QUOTATION_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  SENT: "SENT",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
});

const INVOICE_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  SENT: "SENT",
  PAID: "PAID",
  PARTIALLY_PAID: "PARTIALLY_PAID",
  OVERDUE: "OVERDUE",
  CANCELLED: "CANCELLED",
});

const DOCUMENT_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  ARCHIVED: "ARCHIVED",
  DELETED: "DELETED",
});

const FREQUENCY_TYPE = Object.freeze({
  MONTHLY: "MONTHLY",
  QUARTERLY: "QUARTERLY",
  YEARLY: "YEARLY",
  ONE_TIME: "ONE_TIME",
});

const PAYMENT_MODE = Object.freeze({
  CASH: "CASH",
  UPI: "UPI",
  BANK_TRANSFER: "BANK_TRANSFER",
  CHEQUE: "CHEQUE",
  CARD: "CARD",
});

const PAYMENT_STATUS = Object.freeze({
  INITIATED: "INITIATED",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  PENDING: "PENDING",
});

const REMINDER_STATUS = Object.freeze({
  PENDING: "PENDING",
  SENT: "SENT",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
});

module.exports = {
  ROLES,
  STATUS,
  USER_STATUS,
  CLIENT_STATUS,
  TASK_STATUS,
  PRIORITY,
  QUOTATION_STATUS,
  INVOICE_STATUS,
  DOCUMENT_STATUS,
  FREQUENCY_TYPE,
  REMINDER_STATUS,
  PAYMENT_MODE,
  PAYMENT_STATUS,
};


